### ISSUE TITLE
Previewed element is one color change behind the currently selected color

### ISSUE THREAD

**Issue by daveromsey** [BraadMartin/components#1]
Hello,

First - major thanks for this!

I have run into a little issue while testing this great new RBGa control. While customizin', the target on the live preview is one color selection behind what I've set in the customizer panel. This is happening with the test code [here](https://github.com/BraadMartin/components/blob/master/customizer/customizer.php).

The Current Color box on the RBGA customizer control updates immediately when changing colors, but the element targeted in the JS preview is one color behind. This is hard to notice when dragging the color selection circle around, but the phenomenon can easily be seen when selecting between various color presets or by single clicking different colors in the color selection area.

I'm using the following code to enqueue the JS preview:
```php
function xxx_customizer_preview_js() {
	wp_enqueue_script( 'xxx-customizer-preview', get_stylesheet_directory_uri() . '/js/customizer-preview.js', array( 'customize-preview', 'jquery' ), '0.1.0', true );
}
add_action( 'customize_preview_init', 'xxx_customizer_preview_js' );
```

Here is the contents of the customizer-preview.js file:
```javascript
( function( $ ) {

	wp.customize( 'components_alpha_color_test_setting', function( value ) {
		value.bind( function( to ) {
			$( '.target-element' ).css( 'background-color', to );
		} );
	} );
	
} )( jQuery );
```

**Comment by BraadMartin** [comment]
Thank you @daveromsey for reporting this issue. I am able to reproduce it and will hopefully soon have a fix. During testing I also found some related issues with the color value not updating correctly 100% of the time, so I'll do a full review and push a comprehensive fix as soon as it's ready.

**Comment by BraadMartin** [comment]
@daveromsey I spent some time reworking the way the color value gets passed around through the various functions, and now it's much more solid. The live previewing now works as expected using the customizer-preview.js code that you provided, and I fixed a couple of edge case bugs also. Let me know if the update is working for you, and thanks again for reporting the issue.

**Comment by daveromsey** [comment]
Thanks so much @BraadMartin! I've tried the update, and am happy to report that colors are now changing correctly in all situations. This thing is awesome!
