### ISSUE TITLE
Sanitize Callback

### ISSUE THREAD

**Issue by tsquez** [BraadMartin/components#16]
This is working great in a theme I am building. However when i run the theme through ThemeCheck plugin I get the following error msg:
`REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.`

The only setting I added was the alpha picker.

`// Alpha Color Picker setting.
    $wp_customize->add_setting('alpha_color_setting',
        array(
            'default'    => 'rgb(0, 0, 0,)',
            'type'       => 'theme_mod',
            'capability' => 'edit_theme_options',
            'transport'  => 'postMessage',
            'sanitize_callback' => 'NEEDS TO GO HERE',
        ));`

Any idea how I can add the sanitize callback?

**Comment by red-muppet** [comment]
This is the sanitization function I use, change themename to your theme/plugin

`function themename_sanitize_hex_rgb_rgba_color( $input ) {
    if ( '' === $input ) {
        return '';
    }
    if (
    	preg_match('|^#([A-Fa-f0-9]{3}){1,2}$|', $input )
    	|| preg_match('/\A^rgb\(([0]*[0-9]{1,2}|[1][0-9]{2}|[2][0-4][0-9]|[2][5][0-5])\s*,\s*([0]*[0-9]{1,2}|[1][0-9]{2}|[2][0-4][0-9]|[2][5][0-5])\s*,\s*([0]*[0-9]{1,2}|[1][0-9]{2}|[2][0-4][0-9]|[2][5][0-5])\s*,\s*([0-9]*\.?[0-9]+)\)$\z/im', $input)
    	|| preg_match('/\A^rgba\(([0]*[0-9]{1,2}|[1][0-9]{2}|[2][0-4][0-9]|[2][5][0-5])\s*,\s*([0]*[0-9]{1,2}|[1][0-9]{2}|[2][0-4][0-9]|[2][5][0-5])\s*,\s*([0]*[0-9]{1,2}|[1][0-9]{2}|[2][0-4][0-9]|[2][5][0-5])\s*,\s*([0-9]*\.?[0-9]+)\)$\z/im', $input)
    	) {
        return $input;
    }
}`

...and then call the function in your customizer setting

`// Alpha Color Picker setting. $wp_customize->add_setting('alpha_color_setting', array( 'default' => 'rgb(0, 0, 0,)', 'type' => 'theme_mod', 'capability' => 'edit_theme_options', 'transport' => 'postMessage', 'sanitize_callback' => 'themename_sanitize_hex_rgb_rgba_color', ));`

**Comment by tsquez** [comment]
Thank you very much @red-muppet - I am going to add this and see how well it works. I greatly appreciate the help.

**Comment by BraadMartin** [comment]
Awesome solution @red-muppet! Glad you're finding the Alpha Color Picker useful @tsquez :)
