### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by HardeepAsrani** [BraadMartin/components#18]
I saw an issue with the color picker which will affect user with WordPress 4.9, so are you accepting pull requests? @BraadMartin

**Comment by skyshab** [comment]
I have the same question. I have fixed the issue in my local version, and would be willing to submit a patch.

**Comment by csalzano** [comment]
@skyshab I am interested in seeing your fix, and I don't see a fork on your profile. Do you mind sharing it via a fork?

**Comment by skyshab** [comment]
@mistercorey I will fork and push my fixes sometime today.

**Comment by HardeepAsrani** [comment]
Awesome. I'm working on a library of Customizer controls, so will be taking your changes and modifying it if needed and put it in my library if this library isn't active anymore (of course, I'll give attributes to the contributors): http://github.com/HardeepAsrani/o2/

So far all the controls are made by me, but don't see any point in making a new alpha control when a good one is already out there.

**Comment by skyshab** [comment]
@mistercorey, @HardeepAsrani, 

I forked and pushed my local changes. I am only working with the WordPress customizer Alpha Color Picker, so not sure if the Multi-Color picker needs refactoring. I have also added filters for the scripts and styles enqueueing, so you can change the location in your project without editing the source code. However, if you concat these into your main project files, you still need to remove the enqueue method or unenqueue. It should probably be removed from the control class all together. 

Also, I have custom CSS applied to the controls, which I had to fix for this update. Not sure if the defaults here need any tweaking. 

https://github.com/skyshab/components/blob/master/customizer/alpha-color-picker/alpha-color-picker.php

**Comment by BraadMartin** [comment]
@mistercorey @skyshab @HardeepAsrani 

With Gutenberg on the horizon, and with it including a new color picker field, I haven't been focusing on maintaining the custom controls in this repo. If there are any quick fixes that are needed to get any of these controls working on the latest version of WP feel free to submit PRs and I'll be happy to merge them, or I'm happy to see the many forks that folks have going.

**Comment by mark-8** [comment]
Thanks for your fork @skyshab, works great - why not submit a PR for merge, it'll save people time hunting your fork out.

@BraadMartin, it took me over 18 months to get a [simple hook added in WP core](https://core.trac.wordpress.org/ticket/34034), so waiting for an alpha color picker, even with Gutenberg, might end up being like waiting for the sun to burn up :(

**Comment by bluestockinger** [comment]
@BraadMartin @HardeepAsrani @skyshab @mistercorey @intared 

@skyshab, I forked my own changes from yours after running into some trouble getting this colour picker to work on child themes.

@BraadMartin, I've also submitted a PR for merge with both my own and @skyshab's changes.
