### ISSUE TITLE
Opacity slider does not change opacity until mouse button is released.

### ISSUE THREAD

**Issue by daveromsey** [BraadMartin/components#2]
When changing the opacity value using the opacity slider, I noticed that the opacity changes were not taking effect until the the mouse button was released after moving the slider control. This behavior differs from the native iris color slider, which when changed, updates the Current Color preview immediately. 

I found that by changing the `slidechange` event to `slide` on line 198 of alpha-color-picker.js, that I was able to get the opacity slider to work just like the iris's native saturation slider. I did not notice any negative side effects of this change, but definitely will let you be the judge. :-)

**Comment by BraadMartin** [comment]
Thank you @daveromsey for trying out the control and sharing how it could be improved. You rock!
